### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by wamserma** [jforissier/aesgcm#1]
@jforissier Please add a license. Suggestion: ISC

**Comment by jforissier** [comment]
Hi @wamserma,

There is already a BSD-2-Clause license here: https://github.com/jforissier/aesgcm/blob/master/aesgcm.c#L1

**Comment by wamserma** [comment]
> Hi @wamserma,
> 
> There is already a BSD-2-Clause license here: https://github.com/jforissier/aesgcm/blob/master/aesgcm.c#L1

My fault, overlooked that. Pawlowian reflexes had me look for a LICENSE file.
